# Docker
# Build a Docker image 
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- master


pool:
  vmImage: 'ubuntu-latest'

steps:

- script:
    docker build -t juice-shop .
  displayName: 'Build Docker image'
- task: SnykSecurityScan@0
  inputs:
    serviceConnectionEndpoint: 'snyk'
    testType: 'container'
    dockerImageName: 'juice-shop'
    dockerfilePath: 'Dockerfile'
    monitorOnBuild: true
    failOnIssues: true
    
- task: DockerCompose@0
  displayName: Build services
  inputs:
    action: Build services
    azureSubscription: 'Free Trial (4da184ab-0b2d-4c68-81d7-4d872dd32a02)'
    dockerComposeFile: 'docker-compose.yml'
    projectName: juice-shop
    qualifyImageNames: true