# Docker
# Build a Docker image 
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- master


pool:
  vmImage: 'ubuntu-latest'

steps:

- script:
    docker build -t juice-shop .
  displayName: 'Build Docker image'
- task: SnykSecurityScan@0
  inputs:
    serviceConnectionEndpoint: 'snyk'
    testType: 'container'
    dockerImageName: 'juice-shop'
    dockerfilePath: 'Dockerfile'
    monitorOnBuild: true
    failOnIssues: true
    
- task: DockerCompose@0
  displayName: 'Start NATS Services'
  inputs:
    containerregistrytype: 'Container Registry'
    dockerComposeFile: 'docker-compose.yml'
    action: 'Run a Docker Compose command'
    dockerComposeCommand: 'up -d'

