# Docker
# Build a Docker image 
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- master

resources:
- repo: self

variables:
  tag: '$(Build.BuildId)'
  imageName: 'pipelines-javascript-docker'

stages:
- stage: Build
  displayName: Build image
  jobs:  
  - job: Build
    displayName: Build
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - task: Docker@2
      displayName: Build an image
      inputs:
        command: build
        dockerfile: 'Dockerfile'
        tags: |
          $(tag)

- stage: SnykSecurityScan
  displayName: Snyk
  jobs:
    - job: Snyk
      displayName: Snyk
      steps:
      - task: SnykSecurityScan@0
        inputs:
          serviceConnectionEndpoint: 'snyk'
          testType: 'container'
          dockerImageName: 'juice-shop'
          dockerfilePath: 'Dockerfile'
          monitorOnBuild: true
          failOnIssues: true