# Docker
# Build a Docker image 
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- master

resources:
- repo: self

variables:
  tag: '$(Build.BuildId)'

- script: 
    docker build -t juice-shop .
  displayName: 'build Docker image'

stages:
- stage: Build
  displayName: Build image
  jobs:  
  - job: Build
    displayName: Build
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - task: Docker@2
      displayName: Build an image
      inputs:
        command: build
        dockerfile: '$(Build.SourcesDirectory)/Dockerfile'
        tags: |
          $(tag)

- task: SnykSecurityScan@0
  inputs:
    serviceConnectionEndpoint: 'snyk'
    testType: 'container'
    dockerImageName: 'juice-shop'
    dockerfilePath: 'Dockerfile'
    monitorOnBuild: true
    failOnIssues: true